title: "Píldoras Formativas"
description: "Una colección de recursos y herramientas útiles compartidas periódicamente."
baseurl: ""
url: "https://tu-usuario.github.io"
theme: minima

# Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# Collections
collections:
  pildoras:
    output: true
    permalink: /:collection/:name

# Defaults
defaults:
  - scope:
      path: ""
      type: "pildoras"
    values:
      layout: "pildora"

# Search settings
search_enabled: true

